name: Godot builds

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      
      - name: test
        run: echo test (begin)

        
      - name: Godot Export
        # You may pin to the exact commit or the version.
        # uses: firebelley/godot-export@930577654862a320eef793f399ee911b4479efb9
        uses: firebelley/godot-export@v7.0.0
        with:
          # The download url of the Linux Headless Godot executable.
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_win64.zip
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_mono_export_templates.tpz
          # The path relative to the root of the git repository that contains the "project.godot" file.
          relative_project_path: ./
          # If provided, exports will be moved to this directory relative to the root of the Git repository. This setting is overridden by "use_preset_export_path".
          relative_export_path: release/tmp
          # If "true" the --verbose flag will be added when exporting Godot projects.
          verbose: true
          # Build using Godot 3 executable (NOTE: `godot_executable_download_url` and `godot_export_templates_download_url` still need to be configured to download the correct version.)
          use_godot_3: false

          create_release: true
          
          
      - name: test
        run: echo test (end)
